### ISSUE TITLE
Doesn't compile without adding project location to header search paths

### ISSUE THREAD

**Issue by wouterds** [flowkey/react-native-home-indicator#13]
Hi

I tried linking it manually by adding the generated `.a` product file in build phases but can't seem to get it working without adding the location of the iOS project (the entire path into node modules etc) to my header search paths.

Is that expected to work like that?

**Comment by genkobar** [comment]
Hi wouterds,

I'm just trying this out myself. I figured that [the optional step 3 in the linking guide](http://facebook.github.io/react-native/docs/linking-libraries-ios.html#step-3) is actually required, since the home indicator is managed by the operating system and must thus be native code. It describes adding the header search path, like you mention being necessary.

I guess it wouldn't hurt to mention that in this repo's ReadMe file, to minimize confusion.

**Comment by michaelknoch** [comment]
hey, 

you are totally right, it makes sense to clarify this in our readme. Thanks for pointing out.
Are you cool with this explanation? https://github.com/flowkey/react-native-home-indicator/pull/15
@genkobar @wouterds

**Comment by wouterds** [comment]
Yeah looks good @michaelknoch 👏
